import { OPENAI_EMBEDDING_DIMENSIONS } from "@/lib/openaiEmbeddings";

const DEFAULT_QDRANT_COLLECTION = "documents";

export const LEGACY_QDRANT_COLLECTION =
  process.env.LEGACY_QDRANT_COLLECTION_NAME ||
  process.env.QDRANT_COLLECTION_NAME ||
  DEFAULT_QDRANT_COLLECTION;

export const OPENAI_QDRANT_COLLECTION =
  process.env.OPENAI_QDRANT_COLLECTION_NAME ||
  process.env.QDRANT_COLLECTION_NAME ||
  `${DEFAULT_QDRANT_COLLECTION}_openai_${OPENAI_EMBEDDING_DIMENSIONS}`;
